"""Knowledge service adapter."""

from __future__ import annotations

from typing import Any

from adip.api.rest.adapters.base import BaseServiceAdapter
from adip.api.rest.models.base import ApiResponse

MOCK_DOCS: list[dict[str, Any]] = [
    {"id": "DOC-001", "title": "Solar Panel Maintenance SOP v4", "category": "sop", "status": "published", "content": "## Standard Operating Procedure\n\n### Solar Panel Maintenance\n\n**Scope:** All photovoltaic installations under ADIP management.\n\n**Frequency:** Quarterly inspection with annual deep maintenance.\n\n**Procedure:**\n1. Visual inspection of all panels for cracks, delamination, or discoloration\n2. Thermal imaging scan to identify hot spots\n3. Electrical performance verification (I-V curve tracing)\n4. Cleaning schedule based on soiling index\n5. Connection torque verification\n6. Inverter performance check\n\n**Safety:** LOTO procedures must be followed. All work at height requires harness inspection within last 6 months.", "summary": "Standard operating procedure for quarterly solar panel maintenance including inspection, cleaning, and performance verification.", "author": "Technical Standards Team", "version": 4, "createdAt": "2026-01-15T10:00:00Z", "updatedAt": "2026-06-01T14:30:00Z", "tags": ["solar", "maintenance", "sop", "safety"], "fileSize": 245000, "pageCount": 12, "language": "en", "sourceUrl": "/knowledge/DOC-001", "relatedAssets": ["SP-101", "SP-102", "SP-103"], "relatedEvidence": ["EV-001", "EV-002"], "relatedRecommendations": ["R-001"]},
    {"id": "DOC-002", "title": "Wind Turbine Annual Inspection Checklist", "category": "manual", "status": "published", "content": "# Wind Turbine Annual Inspection Checklist\n\n## Pre-Inspection\n- [ ] Review maintenance history\n- [ ] Check weather forecast (max wind 15m/s)\n- [ ] Prepare tools and replacement parts\n- [ ] Notify grid operator\n\n## Mechanical Systems\n- [ ] Blade surface inspection for erosion/cracks\n- [ ] Pitch bearing check\n- [ ] Yaw system alignment\n- [ ] Gearbox oil analysis sample\n- [ ] Brake pad thickness measurement\n\n## Electrical Systems\n- [ ] Generator insulation resistance\n- [ ] Converter cabinet cleaning\n- [ ] Cable gland torque\n- [ ] Lightning protection system test\n\n## Documentation\n- [ ] Complete inspection report\n- [ ] Upload to ADIP Knowledge Base\n- [ ] Schedule any follow-up repairs", "summary": "Comprehensive annual inspection checklist for wind turbines covering mechanical, electrical, and safety systems.", "author": "Engineering Dept", "version": 3, "createdAt": "2025-11-20T08:00:00Z", "updatedAt": "2026-05-15T09:00:00Z", "tags": ["wind", "inspection", "checklist", "safety"], "fileSize": 180000, "pageCount": 8, "language": "en", "sourceUrl": "/knowledge/DOC-002", "relatedAssets": ["WT-101", "WT-102", "WT-103"], "relatedEvidence": ["EV-003"], "relatedRecommendations": ["R-002"]},
    {"id": "DOC-003", "title": "Transformer Oil Analysis Best Practices", "category": "best_practice", "status": "published", "content": "# Transformer Oil Analysis Best Practices\n\n## Key Parameters\n\n### Dissolved Gas Analysis (DGA)\n- Hydrogen (H\u2082): >100 ppm indicates partial discharge\n- Methane (CH\u2084): >50 ppm indicates arcing\n- Ethylene (C\u2082H\u2084): >100 ppm indicates thermal fault\n- Acetylene (C\u2082H\u2082): >10 ppm indicates severe arcing\n\n### Oil Quality\n- Dielectric strength: >30 kV (new), >20 kV (in service)\n- Moisture content: <20 ppm (new), <35 ppm (in service)\n- Acidity: <0.1 mg KOH/g (in service)\n- Interfacial tension: >25 mN/m\n\n### Sampling Frequency\n- Critical transformers (>100 MVA): quarterly\n- Standard transformers: semi-annual\n- Distribution transformers: annual\n\n### Interpretation\n- Use Duval Triangle method for fault type identification\n- Consider loading history when evaluating results\n- Trending is more valuable than single measurements", "summary": "Best practices for transformer oil analysis including DGA interpretation, oil quality thresholds, and sampling frequency guidelines.", "author": "Laboratory Services", "version": 2, "createdAt": "2025-08-10T12:00:00Z", "updatedAt": "2026-03-20T16:00:00Z", "tags": ["transformer", "oil-analysis", "best-practice", "dga"], "fileSize": 320000, "pageCount": 15, "language": "en", "sourceUrl": "/knowledge/DOC-003", "relatedAssets": ["TF-101", "TF-102", "TF-201"], "relatedEvidence": ["EV-004"], "relatedRecommendations": ["R-003"]},
    {"id": "DOC-004", "title": "ISO 50001 Energy Management Compliance", "category": "compliance", "status": "published", "content": "# ISO 50001:2024 Compliance Framework\n\n## Energy Management System Requirements\n\n### Planning\n- Energy review at defined intervals\n- Energy baseline establishment\n- Energy performance indicators (EnPIs)\n- Objectives and action plans\n\n### Implementation\n- Operational planning and control\n- Design and procurement considerations\n\n### Performance Evaluation\n- Monitoring, measurement, analysis and evaluation\n- Internal audit\n- Management review\n\n### Improvement\n- Nonconformity and corrective action\n- Continual improvement\n\n## Documentation Requirements\n- Scope of EnMS\n- Energy policy\n- Energy planning process\n- Energy review documentation", "summary": "Comprehensive compliance framework for ISO 50001:2024 energy management system certification requirements.", "author": "Compliance Team", "version": 1, "createdAt": "2026-02-01T08:00:00Z", "updatedAt": "2026-02-01T08:00:00Z", "tags": ["compliance", "iso-50001", "energy-management", "certification"], "fileSize": 450000, "pageCount": 22, "language": "en", "sourceUrl": "/knowledge/DOC-004", "relatedAssets": [], "relatedEvidence": ["EV-005", "EV-006"], "relatedRecommendations": []},
    {"id": "DOC-005", "title": "Emergency Response Playbook - Grid Failure", "category": "playbook", "status": "published", "content": "# Emergency Response Playbook: Grid Failure\n\n## Activation Criteria\n- Complete loss of grid connection >5 minutes\n- Partial grid failure affecting >25% of capacity\n- Black start required\n\n## Immediate Actions (First 15 Minutes)\n1. **Isolate failed section** - Open all breakers on affected bus\n2. **Assess situation** - Determine scope and cause\n3. **Notify stakeholders** - Grid operator, key customers, regulatory body\n4. **Activate backup systems** - Battery storage, backup generators\n\n## Recovery Phase\n1. **Black start procedure** - Restart primary generation sources\n2. **Synchronize** - Match phase and frequency\n3. **Reconnect loads** - Prioritize critical infrastructure\n4. **Stabilize** - Monitor frequency and voltage\n\n## Post-Event\n- Incident report within 24 hours\n- Root cause analysis within 7 days\n- Update playbook based on lessons learned", "summary": "Emergency response playbook for grid failure scenarios including immediate actions, recovery procedures, and post-event requirements.", "author": "Emergency Response Team", "version": 5, "createdAt": "2025-06-15T10:00:00Z", "updatedAt": "2026-04-10T11:00:00Z", "tags": ["emergency", "grid-failure", "playbook", "black-start"], "fileSize": 520000, "pageCount": 25, "language": "en", "sourceUrl": "/knowledge/DOC-005", "relatedAssets": ["TF-101", "TF-201", "BB-101"], "relatedEvidence": ["EV-007"], "relatedRecommendations": ["R-004", "R-005"]},
    {"id": "DOC-006", "title": "Battery Storage Safety Guidelines", "category": "policy", "status": "published", "content": "# Battery Storage Safety Guidelines\n\n## General Safety\n- All personnel must complete battery safety training annually\n- PPE: insulated gloves, face shield, flame-resistant clothing\n- No metal jewelry or loose conductive items\n- Two-person rule for all high-voltage work\n\n## Fire Safety\n- Class D fire extinguishers at all battery locations\n- Automatic gas detection and ventilation\n- Thermal runaway detection system\n- Emergency ventilation activation at 60\u00b0C\n\n## Operational Limits\n- Do not exceed 90% SOC for extended periods\n- Minimum SOC: 10% for Li-ion, 20% for flow batteries\n- Operating temperature: 15-35\u00b0C\n- Maximum charge/discharge rate: 1C continuous\n\n## Maintenance\n- Weekly: visual inspection, temperature check\n- Monthly: connection torque check, capacity test\n- Quarterly: BMS firmware update check, calibration", "summary": "Comprehensive safety guidelines for battery storage systems covering operational limits, fire safety, and maintenance procedures.", "author": "Safety Committee", "version": 2, "createdAt": "2025-09-01T09:00:00Z", "updatedAt": "2026-05-01T10:00:00Z", "tags": ["battery", "safety", "guidelines", "training"], "fileSize": 280000, "pageCount": 14, "language": "en", "sourceUrl": "/knowledge/DOC-006", "relatedAssets": ["BB-101", "BB-102", "BB-103"], "relatedEvidence": ["EV-008", "EV-009"], "relatedRecommendations": ["R-006"]},
    {"id": "DOC-007", "title": "Transformer Maintenance Manual - Siemens 2025", "category": "manual", "status": "published", "content": "# Siemens 2025 Transformer Maintenance Manual\n\n## Model Coverage\n- SITRAM 100-500 MVA\n- SITRAM 500-1000 MVA\n- SITRAM Above 1000 MVA\n\n## Maintenance Schedule\n\n### Monthly\n- Oil level check\n- Bushing condition (visual)\n- Cooling system operation\n- Tap changer operation test\n\n### Quarterly\n- Oil sample for DGA\n- Infrared scan of connections\n- Bushing power factor test\n- Cooling system cleaning\n\n### Annual\n- Winding resistance test\n- Insulation power factor\n- Turns ratio test\n- Excitation current test\n- Oil dielectric strength test\n\n### 5-Year\n- Internal inspection\n- Oil filtration/regeneration\n- Gasket replacement\n- ARC (Auto-Transformer ReClosure) valve overhaul", "summary": "Comprehensive maintenance manual for Siemens SITRAM transformers covering monthly, quarterly, annual, and 5-year schedules.", "author": "Siemens Technical Publications", "version": 1, "createdAt": "2025-04-01T08:00:00Z", "updatedAt": "2025-04-01T08:00:00Z", "tags": ["transformer", "siemens", "manual", "maintenance"], "fileSize": 2800000, "pageCount": 145, "language": "en", "sourceUrl": "/knowledge/DOC-007", "relatedAssets": ["TF-101", "TF-102"], "relatedEvidence": ["EV-010"], "relatedRecommendations": ["R-007"]},
    {"id": "DOC-008", "title": "ADIP Platform Architecture Overview", "category": "article", "status": "published", "content": "# ADIP Platform Architecture\n\nThe Agentic Decision Intelligence Platform (ADIP) is a modular, event-driven platform designed for enterprise energy management.\n\n## Core Architecture\n\n### Layer 1: Data Ingestion\n- Multiple data sources (IoT, CRM, SCADA, Manual)\n- Intelligent content classification\n- Automated routing to appropriate modules\n\n### Layer 2: Knowledge & Evidence\n- Knowledge base with version-controlled documents\n- Evidence collection and fusion engine\n- Cross-referencing between knowledge and evidence\n\n### Layer 3: Reasoning & Recommendations\n- Multi-strategy reasoning engine\n- Hypothesis generation and testing\n- Evidence-weighted recommendations\n\n### Layer 4: Decision & Action\n- Decision review workflow\n- Automated action execution\n- Complete audit trail\n\n## Key Design Principles\n- Deterministic placeholders - no external AI dependencies\n- Clean Architecture with dependency injection\n- Event-driven communication between modules\n- Complete traceability across all decisions", "summary": "Overview of ADIP platform architecture covering the four-layer design, key principles, and module interactions.", "author": "Architecture Team", "version": 3, "createdAt": "2025-03-01T10:00:00Z", "updatedAt": "2026-06-15T08:00:00Z", "tags": ["architecture", "platform", "design", "overview"], "fileSize": 890000, "pageCount": 18, "language": "en", "sourceUrl": "/knowledge/DOC-008", "relatedAssets": [], "relatedEvidence": [], "relatedRecommendations": []},
    {"id": "DOC-009", "title": "Customer Service Level Agreement (SLA) Template", "category": "contract", "status": "published", "content": "# Service Level Agreement Template\n\n## Service Levels\n\n| Tier | Response Time | Resolution Time | Uptime |\n|------|---------------|-----------------|--------|\n| Basic | 4 hours | 48 hours | 99.0% |\n| Standard | 2 hours | 24 hours | 99.5% |\n| Premium | 30 minutes | 8 hours | 99.9% |\n| Enterprise | 15 minutes | 4 hours | 99.95% |\n\n## Service Credits\n\n| Uptime | Credit |\n|--------|--------|\n| <99.9% | 5% monthly fee |\n| <99.5% | 10% monthly fee |\n| <99.0% | 25% monthly fee |\n\n## Exclusions\n- Scheduled maintenance (advance notice required)\n- Force majeure events\n- Customer-caused outages\n- Third-party service disruptions", "summary": "Standard SLA template with tier definitions, service credit schedule, and exclusions for ADIP service agreements.", "author": "Legal Department", "version": 2, "createdAt": "2025-05-01T09:00:00Z", "updatedAt": "2026-01-10T14:00:00Z", "tags": ["sla", "contract", "legal", "service-levels"], "fileSize": 150000, "pageCount": 6, "language": "en", "sourceUrl": "/knowledge/DOC-009", "relatedAssets": [], "relatedEvidence": ["EV-011"], "relatedRecommendations": ["R-008"]},
    {"id": "DOC-010", "title": "Predictive Maintenance Using ML - White Paper", "category": "article", "status": "published", "content": "# Predictive Maintenance Using Machine Learning\n\n## Overview\n\nPredictive maintenance uses ML models to predict equipment failures before they occur, reducing unplanned downtime by up to 50%.\n\n## Key Techniques\n\n### Anomaly Detection\n- Autoencoder-based reconstruction error\n- One-Class SVM for novel failure modes\n- Isolation Forest for high-dimensional sensor data\n\n### Remaining Useful Life (RUL) Estimation\n- LSTM networks for time series\n- Gradient boosting with engineered features\n- Weibull distribution with survival analysis\n\n### Classification\n- Random Forest for fault type identification\n- CNN on spectrograms for vibration analysis\n- XGBoost for multi-class failure prediction\n\n## Implementation at ADIP\n- Sensor data ingestion through Evidence pipeline\n- Feature engineering in Knowledge module\n- Reasoning engine evaluates multiple hypotheses\n- Recommendations trigger maintenance actions", "summary": "White paper on predictive maintenance using machine learning techniques applied in the ADIP platform.", "author": "Data Science Team", "version": 1, "createdAt": "2026-03-10T11:00:00Z", "updatedAt": "2026-03-10T11:00:00Z", "tags": ["machine-learning", "predictive-maintenance", "white-paper", "ml"], "fileSize": 1200000, "pageCount": 35, "language": "en", "sourceUrl": "/knowledge/DOC-010", "relatedAssets": ["WT-101", "TF-101", "BB-101"], "relatedEvidence": ["EV-012", "EV-013"], "relatedRecommendations": ["R-009", "R-010"]},
]


class KnowledgeAdapter(BaseServiceAdapter):
    def get_domain(self) -> str:
        return "knowledge"

    def ingest(self, document: dict[str, Any] | None = None) -> Any:
        return self._success_response(data={"document_id": "doc-001", "status": "ingested", "document": document or {}})

    def query(
        self,
        q: str = "",
        category: str | None = None,
        status: str | None = None,
        page: int = 1,
        limit: int = 12,
    ) -> ApiResponse:
        items = MOCK_DOCS
        if category:
            items = [d for d in items if d["category"] == category]
        if status:
            items = [d for d in items if d["status"] == status]
        if q:
            query = q.lower()
            items = [d for d in items if query in d["title"].lower() or query in d["content"].lower() or any(query in t.lower() for t in d["tags"])]
        total = len(items)
        start = (page - 1) * limit
        return self._success_response(data={"results": items[start:start + limit], "total": total})

    def get_document(self, document_id: str) -> ApiResponse:
        for doc in MOCK_DOCS:
            if doc["id"] == document_id:
                return self._success_response(data=doc)
        return self._success_response(data=None)

    def delete_document(self, document_id: str) -> Any:
        return self._success_response(data={"document_id": document_id, "status": "deleted"})
